site_name: RmediatoR
site_author: Fikernew Birhanu
copyright: Copyright &copy; 2024 <a href="https://twitter.com/ffekirnew">Fikernew Birhanu</a>.

nav:
  - Home: index.md
  - About: about.md

theme:
  logo: assets/images/rmediator.png
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
